### ISSUE TITLE
Installation instructions don't work -- outdated?

### ISSUE THREAD

**Issue by jeffstearns** [ablyler/home-assistant-bradford-white-connect#16]
## Version of the custom_component

Component not installed.

## Configuration

Component not configured.

## Describe the bug

The installation instructions can't be followed as written.

I already use HACS so it is installed.

But these instructions can't be followed because HACS -> Integrations doesn't exist:
```
In Home Assistant, go to HACS -> Integrations, click on + Explore & Download Repositories, search for Bradford White Connect, and click download. After download, restart Home Assistant.
```

Likewise, the "ADD INTEGRATION TO MY HOME ASSISTANT" button does not work.

I suspect that recent Home Assistant changes are responsible for the disparity.

My current Home Assistant version:
Core 2024.5.3
Supervisor 2024.05.1
Operating System 12.3
Frontend 20240501.1

## Debug log

```
Not applicable, but the issue bot demands text here.
```

**Comment by almoney** [comment]
Go to HACS then add "ablyler/home-assistant-bradford-white-connect" to custom repositories as an integration.  Then download for HACS and restart Home Assistant.  You will then see Bradford White Connect in the integrations to add in Devices and Settings.

**Comment by ablyler** [comment]
Thanks @almoney! That is precisely what must be done until https://github.com/hacs/default/pull/2391 is approved and merged. Do you mind putting up a PR to update the README.md with these instructions as well?

**Comment by ablyler** [comment]
> I have submitted the PR.

Awesome, thanks so much!
