### ISSUE TITLE
temperature reading/control suddenly unavailable

### ISSUE THREAD

**Issue by louiehummv** [ablyler/home-assistant-bradford-white-connect#18]
Installed v.0.2.5 on Home Assistant v.2023.9.3 via HACS v.1.34.0.

As of 4:30pm ET yesterday, the temperature reading/control is showing unavailable. The kWh energy readings, however, are still updating fine for whatever reason. Re-enabling, reloading, & re-adding the component didn't fix it, and restarting HA didn't help either. Enabling the debug logs before performing the aforementioned also didn't produce an error.

I guess I'll try power-cycling the BW Connect adapter & get back to you. Just figured I'd bring attention to this, in case you know of something else going on behind-the-scenes to the BW servers or something (I'm the opposite of an expert in that area).

**Comment by ablyler** [comment]
Does the BWConnect app still work? I've found that the adapter does need power cycled from time to time to resolve these issues. When it becomes unavailable in HA it is also not working via the BWConnect mobile app for me. 

I actually have an automation that power cycles the adapter via a smart plug. I should add a note about this to the README. 

Keep me posted on this, I am curious if cycling the power fixes it.

**Comment by louiehummv** [comment]
Cycling the power fixed it immediately 👍
 I did find the "action" LED (one closest to the action button) blinking blue.. which means "bluetooth activated; pairing process begins" according to the manual. No idea why/how the adapter went to that state on its own. It's now solid green (powered & connected to Internet).

I didn't think to test the BWConnect app beforehand.. mainly because the app appeared to working with the temperature setpoint & mode looking as expected. In hindsight though, they're probably not _live_ readings from the water heater.

**Comment by almoney** [comment]
I've been using my new connected water heater for a week without issues. Could power surges or hits be affecting your units?

**Comment by almoney** [comment]
My unit has been dropping off and on my wifi since Friday, 2 August 2024.  Is anyone else seeing issues?  A power off on establishes access for a short while today. Issue in the Bradford White app as well.

**Comment by ablyler** [comment]
@almoney, yes, my unit will be stable for a long time and then have issues. My automation to cycle the power has been fixing the issue for me.

**Comment by almoney** [comment]
I continue to see the drops.  I am wondering if the code can't stand NAT or FW issues.  I am trying to get the BW guys to check my device to see if I can get them to care about the frequent drop outs.
You can see that it is out every few minutes:
![image](https://github.com/user-attachments/assets/e21f403e-a594-414b-85de-ea69cfcf0111)

**Comment by almoney** [comment]
Quick update: I think this must be a problem with the BW backend.  I wonder what customers do that are not using a smart home monitor to keep it connected?
