### ISSUE TITLE
Ability to set the "Vacation Day" counter

### ISSUE THREAD

**Issue by almoney** [ablyler/home-assistant-bradford-white-connect#22]
On the Water Heater you can set Vacation mode ("Off or Away") to a count of days.   Is there any way we could add this to the app with a calendar setup?  This is what I had with the GE GeoSpring Water heater interface.

**Comment by ablyler** [comment]
Hi @almoney! That is something you could do with an automation in Home Assistant, you could even have an automation hooked up to your Google Calendar that looks for a specific event to trigger this. I hope this help!
