### ISSUE TITLE
Error on action: 'HomeAssistant' object has no attribute 'time'

### ISSUE THREAD

**Issue by super7oas7** [ablyler/home-assistant-bradford-white-connect#24]
Hey there, thanks for making this!

Im running 0.2.9 on HAOS 13.2 and Core 2024.11.3

Im getting an error with every kind of action (temp change, mode change, etc). Sometimes the action seems to be successful, sometimes not. Strange!

> Failed to perform the action water_heater/set_operation_mode. 'HomeAssistant' object has no attribute 'time'

Is this a known issue or am I doing something stupid?

**Comment by ablyler** [comment]
It looks like there was an issue with the release that just got pushed, I'm working on a fix and should have it out shortly!

**Comment by super7oas7** [comment]
That seems to have worked! Thanks! Minor nit: the version number in the integration details in HA's UI still says "0.2.9"
